# Generated by Django 6.0.3 on 2026-05-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission_statement", models.TextField()),
                ("pastor_name", models.CharField(max_length=100)),
                ("pastor_bio", models.TextField()),
                ("pastor_photo", models.ImageField(blank=True, upload_to="about/")),
                ("value_1_title", models.CharField(max_length=100)),
                ("value_1_body", models.TextField()),
                ("value_2_title", models.CharField(max_length=100)),
                ("value_2_body", models.TextField()),
                ("value_3_title", models.CharField(max_length=100)),
                ("value_3_body", models.TextField()),
                ("value_4_title", models.CharField(max_length=100)),
                ("value_4_body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="events/")),
                ("registration_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("subheadline", models.CharField(max_length=300)),
                ("cta_primary_text", models.CharField(max_length=100)),
                ("cta_primary_url", models.CharField(max_length=200)),
                ("cta_secondary_text", models.CharField(blank=True, max_length=100)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=200)),
                ("background_image", models.ImageField(blank=True, upload_to="hero/")),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="ministry/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Ministries",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SermonSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.ImageField(blank=True, upload_to="series/")),
            ],
            options={
                "verbose_name_plural": "Sermon Series",
            },
        ),
        migrations.CreateModel(
            name="ServiceTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campus_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("times", models.TextField()),
                ("is_online", models.BooleanField(default=False)),
                ("link_label", models.CharField(max_length=100)),
                ("link_url", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pastor", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("youtube_url", models.URLField()),
                ("thumbnail", models.ImageField(blank=True, upload_to="sermons/")),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("faith", "Faith"),
                            ("family", "Family"),
                            ("purpose", "Purpose"),
                            ("prayer", "Prayer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.sermonseries",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
