# Generated by Django 6.0.5 on 2026-05-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="news/")),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-date"],
            },
        ),
    ]
