# Generated by Django 6.0.3 on 2026-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_liturgi"),
    ]

    operations = [
        migrations.CreateModel(
            name="WartaJemaat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("content", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="warta/")),
                ("pdf_file", models.FileField(blank=True, upload_to="warta_pdf/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("warta", "Warta Mingguan"),
                            ("berita", "Berita Jemaat"),
                            ("pengumuman", "Pengumuman"),
                        ],
                        default="warta",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Warta Jemaat",
                "ordering": ["-date"],
            },
        ),
    ]
