# Generated by Django 6.0.5 on 2026-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_album_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("contact", "Kontak Umum"),
                            ("prayer", "Permintaan Doa"),
                        ],
                        default="contact",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
