# Generated by Django 6.0.5 on 2026-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetime",
            name="is_live_now",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicetime",
            name="youtube_live_url",
            field=models.URLField(blank=True),
        ),
    ]
