# Generated by Django 6.0.5 on 2026-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_servicetime_is_live_now_servicetime_youtube_live_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Liturgi",
        ),
        migrations.AlterField(
            model_name="wartajemaat",
            name="category",
            field=models.CharField(
                choices=[
                    ("warta", "Warta Mingguan"),
                    ("berita", "Berita Jemaat"),
                    ("pengumuman", "Pengumuman"),
                    ("liturgi", "Liturgi"),
                ],
                default="warta",
                max_length=20,
            ),
        ),
    ]
