# Generated by Django 6.0.5 on 2026-05-26 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_remove_liturgi_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
