# Generated by Django 6.0.5 on 2026-05-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_remove_news_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_1_body",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_1_title",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_2_body",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_2_title",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_3_body",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_3_title",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_4_body",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="value_4_title",
        ),
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="website.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
