# Generated by Django 6.0.5 on 2026-06-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_flexible_about_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("faith", "Faith"),
                    ("family", "Family"),
                    ("purpose", "Purpose"),
                    ("prayer", "Prayer"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wartajemaat",
            name="category",
            field=models.CharField(
                choices=[
                    ("warta", "Warta Mingguan"),
                    ("pengumuman", "Pengumuman"),
                    ("liturgi", "Liturgi"),
                ],
                db_index=True,
                default="warta",
                max_length=20,
            ),
        ),
    ]
