# Generated by Django 6.0.5 on 2026-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_alter_sermon_topic_alter_wartajemaat_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="wartajemaat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
