# Generated by Django 6.0.5 on 2026-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0012_album_created_at_event_created_at_sermon_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name="wartajemaat",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
    ]
