# Generated by Django 6.0.5 on 2026-06-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_unique_slug_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pendeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("jabatan", models.CharField(default="Gembala Jemaat", max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("foto", models.ImageField(blank=True, upload_to="about/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendeta",
                        to="website.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
