# Generated by Django 6.0.5 on 2026-06-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_pendeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="wartajemaat",
            name="category",
            field=models.CharField(
                choices=[
                    ("warta", "Warta Mingguan"),
                    ("pengumuman", "Pengumuman"),
                    ("liturgi", "Liturgi"),
                    ("bahan", "Bahan"),
                ],
                db_index=True,
                default="warta",
                max_length=20,
            ),
        ),
        # Old topic column is VARCHAR NOT NULL — can't set NULL directly.
        # Manually recreate the table with topic_id as a nullable FK,
        # explicitly inserting NULL for all rows.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE "website_sermon_new" (
                            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                            "title" varchar(200) NOT NULL,
                            "pastor" varchar(100) NOT NULL,
                            "date" date NOT NULL,
                            "description" text NOT NULL,
                            "youtube_url" varchar(200) NOT NULL,
                            "thumbnail" varchar(100) NOT NULL,
                            "is_featured" bool NOT NULL,
                            "topic_id" bigint NULL REFERENCES "website_topic" ("id") DEFERRABLE INITIALLY DEFERRED,
                            "series_id" bigint NULL REFERENCES "website_sermonseries" ("id") DEFERRABLE INITIALLY DEFERRED,
                            "created_at" datetime NULL,
                            "slug" varchar(220) NOT NULL UNIQUE
                        );
                        INSERT INTO "website_sermon_new"
                            ("id", "title", "pastor", "date", "description", "youtube_url",
                             "thumbnail", "is_featured", "topic_id", "series_id", "created_at", "slug")
                        SELECT
                            "id", "title", "pastor", "date", "description", "youtube_url",
                            "thumbnail", "is_featured", NULL, "series_id", "created_at", "slug"
                        FROM "website_sermon";
                        DROP TABLE "website_sermon";
                        ALTER TABLE "website_sermon_new" RENAME TO "website_sermon";
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="sermon",
                    name="topic",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.topic",
                    ),
                ),
            ],
        ),
    ]
