# Generated by Django 6.0.5 on 2026-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_topic_alter_wartajemaat_category_alter_sermon_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
