# Generated by Django 6.0.5 on 2026-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_alter_sermon_youtube_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="pastor_bio",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="pastor_name",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="pastor_photo",
        ),
    ]
