# Generated by Django 6.0.5 on 2026-05-12 07:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IbadahMingguan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(unique=True)),
                ("minggu_ke", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Ibadah Mingguan",
                "verbose_name_plural": "Ibadah Mingguan",
                "ordering": ["-tanggal"],
            },
        ),
        migrations.CreateModel(
            name="Keluarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_kk_gereja", models.CharField(max_length=20, unique=True)),
                ("nama_keluarga", models.CharField(max_length=200)),
                (
                    "blok",
                    models.CharField(
                        choices=[
                            ("CK1", "CK1"),
                            ("CK2", "CK2"),
                            ("CK3", "CK3"),
                            ("GT1", "GT1"),
                            ("GT2", "GT2"),
                            ("JS1", "JS1"),
                            ("JS2", "JS2"),
                            ("JS3", "JS3"),
                            ("KD1", "KD1"),
                            ("KD2", "KD2"),
                            ("KP1", "KP1"),
                            ("KP2", "KP2"),
                            ("KS1", "KS1"),
                            ("KS2", "KS2"),
                            ("KT1", "KT1"),
                            ("KT2", "KT2"),
                            ("KT3", "KT3"),
                            ("KW1", "KW1"),
                            ("KW2", "KW2"),
                            ("KY1", "KY1"),
                            ("KY2", "KY2"),
                            ("KY3", "KY3"),
                            ("KY4", "KY4"),
                            ("KY5", "KY5"),
                        ],
                        max_length=10,
                    ),
                ),
                ("alamat", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Keluarga",
                "ordering": ["nama_keluarga"],
            },
        ),
        migrations.CreateModel(
            name="IbadahService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_service", models.CharField(max_length=100)),
                ("jumlah_hadir", models.PositiveIntegerField(default=0)),
                (
                    "jumlah_persembahan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ibadah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="members.ibadahmingguan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("no_sensus", models.CharField(db_index=True, max_length=20)),
                ("nama_lengkap", models.CharField(max_length=200)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("tempat_lahir", models.CharField(blank=True, max_length=100)),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                ("nomor_telepon", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("Dewasa", "Dewasa"), ("Anak", "Anak")],
                        default="Dewasa",
                        max_length=10,
                    ),
                ),
                (
                    "kewargaan",
                    models.CharField(
                        choices=[
                            ("Warga", "Warga"),
                            ("Simpatisan", "Simpatisan"),
                            ("Titipan", "Titipan"),
                            ("Luar Kota", "Luar Kota"),
                            ("Meninggal", "Meninggal"),
                        ],
                        default="Warga",
                        max_length=20,
                    ),
                ),
                (
                    "gol_darah",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("AB", "AB"),
                            ("O", "O"),
                            ("-", "Tidak Diketahui"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "pendidikan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("D3", "D3"),
                            ("S1", "S1"),
                            ("S2", "S2"),
                            ("S3", "S3"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pekerjaan", models.CharField(blank=True, max_length=100)),
                (
                    "ket_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KK", "Kepala Keluarga"),
                            ("Istri", "Istri"),
                            ("Anak", "Anak"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sudah_baptis", models.BooleanField(default=False)),
                ("sudah_sidi", models.BooleanField(default=False)),
                ("tanggal_wafat", models.DateField(blank=True, null=True)),
                ("pelayanan_diikuti", models.TextField(blank=True)),
                ("ibadah_sering_diikuti", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "keluarga",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="members.keluarga",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical member",
                "verbose_name_plural": "historical members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_sensus", models.CharField(max_length=20, unique=True)),
                ("nama_lengkap", models.CharField(max_length=200)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("tempat_lahir", models.CharField(blank=True, max_length=100)),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                ("nomor_telepon", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("Dewasa", "Dewasa"), ("Anak", "Anak")],
                        default="Dewasa",
                        max_length=10,
                    ),
                ),
                (
                    "kewargaan",
                    models.CharField(
                        choices=[
                            ("Warga", "Warga"),
                            ("Simpatisan", "Simpatisan"),
                            ("Titipan", "Titipan"),
                            ("Luar Kota", "Luar Kota"),
                            ("Meninggal", "Meninggal"),
                        ],
                        default="Warga",
                        max_length=20,
                    ),
                ),
                (
                    "gol_darah",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("AB", "AB"),
                            ("O", "O"),
                            ("-", "Tidak Diketahui"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "pendidikan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("D3", "D3"),
                            ("S1", "S1"),
                            ("S2", "S2"),
                            ("S3", "S3"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pekerjaan", models.CharField(blank=True, max_length=100)),
                (
                    "ket_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KK", "Kepala Keluarga"),
                            ("Istri", "Istri"),
                            ("Anak", "Anak"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sudah_baptis", models.BooleanField(default=False)),
                ("sudah_sidi", models.BooleanField(default=False)),
                ("tanggal_wafat", models.DateField(blank=True, null=True)),
                ("pelayanan_diikuti", models.TextField(blank=True)),
                ("ibadah_sering_diikuti", models.TextField(blank=True)),
                (
                    "keluarga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="members.keluarga",
                    ),
                ),
            ],
            options={
                "ordering": ["nama_lengkap"],
            },
        ),
        migrations.CreateModel(
            name="Majelis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jabatan",
                    models.CharField(
                        choices=[
                            ("Pendeta", "Pendeta"),
                            ("Penatua", "Penatua"),
                            ("Diaken", "Diaken"),
                            ("Wiyata", "Wiyata"),
                        ],
                        max_length=20,
                    ),
                ),
                ("periode_mulai", models.DateField()),
                ("periode_selesai", models.DateField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="majelis_records",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Majelis",
            },
        ),
        migrations.CreateModel(
            name="IuranPralenan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "metode_pembayaran",
                    models.CharField(
                        choices=[
                            ("Tunai", "Tunai"),
                            ("Transfer", "Transfer"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iuran_pralenan",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Iuran Pralenan",
                "ordering": ["-tanggal"],
            },
        ),
        migrations.CreateModel(
            name="MemberStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_lama", models.CharField(max_length=20)),
                ("status_baru", models.CharField(max_length=20)),
                ("keterangan", models.TextField(blank=True)),
                ("tanggal", models.DateField(auto_now_add=True)),
                (
                    "dicatat_oleh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Member Status History",
                "ordering": ["-tanggal"],
            },
        ),
        migrations.CreateModel(
            name="Perpuluhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "metode_pembayaran",
                    models.CharField(
                        choices=[
                            ("Tunai", "Tunai"),
                            ("Transfer", "Transfer"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perpuluhan",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Perpuluhan",
                "ordering": ["-tanggal"],
            },
        ),
    ]
