# Generated by Django 6.0.5 on 2026-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keluarga",
            name="blok",
            field=models.CharField(
                choices=[
                    ("CK1", "CK1"),
                    ("CK2", "CK2"),
                    ("CK3", "CK3"),
                    ("GD1", "GD1"),
                    ("JT1", "JT1"),
                    ("JT2", "JT2"),
                    ("JT3", "JT3"),
                    ("JT4", "JT4"),
                    ("JB1", "JB1"),
                    ("JB2", "JB2"),
                    ("JB3", "JB3"),
                    ("JB4", "JB4"),
                    ("JB5", "JB5"),
                    ("KM1", "KM1"),
                    ("KM2", "KM2"),
                    ("KM3", "KM1"),
                    ("KM4", "KM4"),
                    ("KM5", "KM5"),
                    ("KY1", "KY1"),
                    ("KY2", "KY2"),
                    ("KY3", "KY3"),
                    ("KY4", "KY4"),
                    ("KY5", "KY5"),
                ],
                max_length=10,
            ),
        ),
    ]
