# Generated by Django 6.0.5 on 2026-06-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_keluarga_blok"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmember",
            name="kewargaan",
            field=models.CharField(
                choices=[
                    ("Warga", "Warga"),
                    ("Simpatisan", "Simpatisan"),
                    ("Titipan", "Titipan"),
                    ("Luar Kota", "Luar Kota"),
                    ("Meninggal", "Meninggal"),
                ],
                db_index=True,
                default="Warga",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="tanggal_lahir",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="keluarga",
            name="blok",
            field=models.CharField(
                choices=[
                    ("CK1", "CK1"),
                    ("CK2", "CK2"),
                    ("CK3", "CK3"),
                    ("GD1", "GD1"),
                    ("JT1", "JT1"),
                    ("JT2", "JT2"),
                    ("JT3", "JT3"),
                    ("JT4", "JT4"),
                    ("JB1", "JB1"),
                    ("JB2", "JB2"),
                    ("JB3", "JB3"),
                    ("JB4", "JB4"),
                    ("JB5", "JB5"),
                    ("KM1", "KM1"),
                    ("KM2", "KM2"),
                    ("KM3", "KM3"),
                    ("KM4", "KM4"),
                    ("KM5", "KM5"),
                    ("KY1", "KY1"),
                    ("KY2", "KY2"),
                    ("KY3", "KY3"),
                    ("KY4", "KY4"),
                    ("KY5", "KY5"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="kewargaan",
            field=models.CharField(
                choices=[
                    ("Warga", "Warga"),
                    ("Simpatisan", "Simpatisan"),
                    ("Titipan", "Titipan"),
                    ("Luar Kota", "Luar Kota"),
                    ("Meninggal", "Meninggal"),
                ],
                db_index=True,
                default="Warga",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="tanggal_lahir",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
