# Generated by Django 6.0.5 on 2026-06-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_historicalmember_kewargaan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="alamat_domisili",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="alamat_ktp",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="baptis_oleh",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="minat_pelayanan_gerejawi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="minat_pelayanan_umum",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="nama_gereja_lain",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="nikah_oleh",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="sidi_oleh",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="status_perkawinan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Belum Menikah", "Belum Menikah"),
                    ("Menikah", "Menikah"),
                    ("Janda", "Janda"),
                    ("Duda", "Duda"),
                    ("Single Parent", "Single Parent"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="status_rumah_tinggal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Milik Sendiri", "Milik Sendiri"),
                    ("Milik Orang Tua", "Milik Orang Tua"),
                    ("Milik Saudara", "Milik Saudara"),
                    ("Kontrak", "Kontrak/Sewa"),
                    ("Menumpang", "Menumpang"),
                    ("Panti", "Panti"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="tanggal_baptis",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="tanggal_nikah",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="tanggal_sidi",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="tempat_baptis",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="tempat_kebaktian",
            field=models.CharField(
                blank=True,
                choices=[("Induk", "Induk"), ("Gereja Lain", "Gereja Lain")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="tempat_nikah",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="tempat_sidi",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="alamat_domisili",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="alamat_ktp",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="baptis_oleh",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="minat_pelayanan_gerejawi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="minat_pelayanan_umum",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="nama_gereja_lain",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="nikah_oleh",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="sidi_oleh",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="status_perkawinan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Belum Menikah", "Belum Menikah"),
                    ("Menikah", "Menikah"),
                    ("Janda", "Janda"),
                    ("Duda", "Duda"),
                    ("Single Parent", "Single Parent"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="status_rumah_tinggal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Milik Sendiri", "Milik Sendiri"),
                    ("Milik Orang Tua", "Milik Orang Tua"),
                    ("Milik Saudara", "Milik Saudara"),
                    ("Kontrak", "Kontrak/Sewa"),
                    ("Menumpang", "Menumpang"),
                    ("Panti", "Panti"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="tanggal_baptis",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="tanggal_nikah",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="tanggal_sidi",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="tempat_baptis",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="tempat_kebaktian",
            field=models.CharField(
                blank=True,
                choices=[("Induk", "Induk"), ("Gereja Lain", "Gereja Lain")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="tempat_nikah",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="tempat_sidi",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="ket_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KK", "Kepala Keluarga"),
                    ("Istri", "Istri"),
                    ("Anak", "Anak"),
                    ("Cucu", "Cucu"),
                    ("Nenek", "Nenek"),
                    ("Saudara", "Saudara"),
                    ("Lainnya", "Lainnya"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="kewargaan",
            field=models.CharField(
                choices=[
                    ("Warga", "Warga"),
                    ("Simpatisan", "Simpatisan"),
                    ("Titipan", "Titipan"),
                    ("Luar Kota", "Luar Kota"),
                    ("Tamu", "Tamu"),
                    ("Meninggal", "Meninggal"),
                ],
                db_index=True,
                default="Warga",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="pendidikan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tidak Sekolah", "Tidak Sekolah"),
                    ("SD", "SD/Sederajat"),
                    ("SMP", "SMP/Sederajat"),
                    ("SMA", "SMA/Sederajat"),
                    ("D1", "D1"),
                    ("D2", "D2"),
                    ("D3", "D3"),
                    ("D4", "D4"),
                    ("S1", "S1"),
                    ("S2", "S2"),
                    ("S3", "S3"),
                    ("Lainnya", "Lainnya"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("Anak", "Anak (< 12 tahun)"),
                    ("Remaja", "Remaja (13–17 tahun)"),
                    ("Pemuda", "Pemuda (18–25 tahun)"),
                    ("Keluarga Muda", "Keluarga Muda (26–40 tahun)"),
                    ("Dewasa", "Dewasa (41–60 tahun)"),
                    ("Adiyuswa", "Adiyuswa (> 60 tahun)"),
                ],
                default="Dewasa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="ket_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KK", "Kepala Keluarga"),
                    ("Istri", "Istri"),
                    ("Anak", "Anak"),
                    ("Cucu", "Cucu"),
                    ("Nenek", "Nenek"),
                    ("Saudara", "Saudara"),
                    ("Lainnya", "Lainnya"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="kewargaan",
            field=models.CharField(
                choices=[
                    ("Warga", "Warga"),
                    ("Simpatisan", "Simpatisan"),
                    ("Titipan", "Titipan"),
                    ("Luar Kota", "Luar Kota"),
                    ("Tamu", "Tamu"),
                    ("Meninggal", "Meninggal"),
                ],
                db_index=True,
                default="Warga",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="pendidikan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tidak Sekolah", "Tidak Sekolah"),
                    ("SD", "SD/Sederajat"),
                    ("SMP", "SMP/Sederajat"),
                    ("SMA", "SMA/Sederajat"),
                    ("D1", "D1"),
                    ("D2", "D2"),
                    ("D3", "D3"),
                    ("D4", "D4"),
                    ("S1", "S1"),
                    ("S2", "S2"),
                    ("S3", "S3"),
                    ("Lainnya", "Lainnya"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("Anak", "Anak (< 12 tahun)"),
                    ("Remaja", "Remaja (13–17 tahun)"),
                    ("Pemuda", "Pemuda (18–25 tahun)"),
                    ("Keluarga Muda", "Keluarga Muda (26–40 tahun)"),
                    ("Dewasa", "Dewasa (41–60 tahun)"),
                    ("Adiyuswa", "Adiyuswa (> 60 tahun)"),
                ],
                default="Dewasa",
                max_length=20,
            ),
        ),
    ]
